# Generated by Django 6.0.3 on 2026-05-26 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название темы')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Легкий'), (2, 'Средний'), (3, 'Сложный')], default=2, verbose_name='Уровень сложности')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='generator.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', 'Выбор одного варианта'), ('open', 'Открытый вопрос')], max_length=20, verbose_name='Тип вопроса')),
                ('text_template', models.TextField(verbose_name='Текст вопроса')),
                ('correct_answer_template', models.CharField(blank=True, max_length=500, verbose_name='Шаблон ответа')),
                ('options_template', models.JSONField(blank=True, null=True, verbose_name='Варианты ответов')),
                ('points', models.IntegerField(default=1, verbose_name='Баллы')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='generator.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Шаблон вопроса',
                'verbose_name_plural': 'Шаблоны вопросов',
            },
        ),
        migrations.CreateModel(
            name='GeneratedWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('variant_count', models.IntegerField(default=4, verbose_name='Количество вариантов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='works/', verbose_name='PDF файл')),
                ('answers_file', models.FileField(blank=True, null=True, upload_to='answers/', verbose_name='PDF с ответами')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='docx/', verbose_name='DOCX файл')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.subject', verbose_name='Предмет')),
                ('topics', models.ManyToManyField(to='generator.topic', verbose_name='Темы')),
            ],
            options={
                'verbose_name': 'Сгенерированная работа',
                'verbose_name_plural': 'Сгенерированные работы',
                'ordering': ['-created_at'],
            },
        ),
    ]
